### ISSUE TITLE
Wrong Button OnTap When radius <75

### ISSUE THREAD

**Issue by jemariads** [hasan-hm1/circular_menu#3]
hi,

I found your widget have a bug, the on tap function button execute wrong button when CircularMenu Radius < 75.

<img width="110" alt="Screen Shot 2020-05-20 at 22 13 05" src="https://user-images.githubusercontent.com/16384852/82464479-5822fe80-9ae8-11ea-8e15-382629dd9db7.png">

When I tapped on black area on red button that execute orange button onTap.

btw thank you for great widget

**Comment by hasan-hm1** [comment]
Hi
Thank you for opening this issue,

This is happening because CircularMenuItem under the hood is RawMaterialButton which has a default padding makes the tappable area expands.

when the menu items get close to each other (for radius < 75 ), the tappable areas overlap causing this issue.

Please check the updated version which removes the default padding so that this issue won't  happen anymore.

Thanks for the feedback.

**Comment by jemariads** [comment]
thank you @hasan-hm1
